// screens/inbox/TaskItemStyles.js
// Estilos de TaskItem.js
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    marginBottom: 8,
    marginHorizontal: 14,
    borderRadius: 16,
    padding: 14,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 0.5,
    position: 'relative',
    overflow: 'hidden',
  },
  // Teléfono: la tarjeta ocupa el ancho de la lista (el margen lo pone la pantalla)
  containerPhone: {
    marginHorizontal: 0,
    padding: 12,
  },
  topAccentBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    zIndex: 2,
    pointerEvents: 'none',
  },
  dueAlert: {
    position: 'absolute',
    top: 6,
    right: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  // Aviso de vencimiento dentro del texto (teléfono)
  dueChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    flexShrink: 0,
  },
  badgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    columnGap: 8,
    rowGap: 6,
  },
  statusTextInline: {
    fontSize: 12,
    fontWeight: '500',
    fontStyle: 'italic',
  },
  dueAlertText: {
    color: '#FFF',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
    gap: 5,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 2,
  },
  avatar: {
    marginRight: 8,
  },
  title: { 
    fontSize: 16, 
    fontWeight: '700', 
    flex: 1, 
    marginRight: 8,
    letterSpacing: -0.3,
    lineHeight: 21,
  },
  titleCompleted: {
    textDecorationLine: 'line-through',
    opacity: 0.6,
  },
  meta: { 
    fontSize: 14, 
    fontWeight: '500',
    letterSpacing: 0.1,
    marginBottom: 6,
  },
  coordinationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    marginBottom: 6,
    borderWidth: 1,
    gap: 6,
    alignSelf: 'flex-start',
  },
  coordinationText: {
    fontSize: 12,
    fontWeight: '600',
  },
  statusText: { 
    fontSize: 12, 
    fontWeight: '500',
    fontStyle: 'italic',
    flex: 1,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
    marginBottom: 2,
  },
  tagChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  tagText: {
    fontSize: 12,
    fontWeight: '600',
  },
  tagMore: {
    fontSize: 12,
    fontWeight: '500',
    paddingVertical: 3,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
  },
  progressBarWrap: {
    flex: 1,
  },
  progressValue: {
    fontSize: 12,
    fontWeight: '700',
    minWidth: 32,
    textAlign: 'right',
  },
  completeAction: {
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingRight: 20,
    borderRadius: 16,
    marginBottom: 12,
    marginRight: 16,
    overflow: 'hidden'
  },
  deleteAction: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 20,
    borderRadius: 16,
    marginBottom: 12,
    marginLeft: 16,
    overflow: 'hidden'
  },
  actionGradient: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  actionContent: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 70
  },
  actionText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5
  },
  contentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  contentRowPhone: {
    gap: 10,
  },
  taskContent: {
    flex: 1,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
    marginTop: 16,
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 10,
  },
  footerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  // Mismo tamaño para chat y eliminar cuando van apilados
  actionBtnPhone: {
    padding: 0,
    width: 40,
    height: 40,
    minWidth: 40,
    minHeight: 40,
    marginTop: 0,
  },
  chatButton: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.04)',
    borderWidth: 0.5,
    borderColor: 'rgba(0,0,0,0.08)',
    minWidth: 38,
    minHeight: 38,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  chatUnreadDot: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 7,
    height: 7,
    borderRadius: 99,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  deleteButton: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 59, 48, 0.10)',
    borderWidth: 0.5,
    borderColor: 'rgba(255,59,48,0.20)',
    minWidth: 44,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  // ⚡ ESTILOS PARA INDICADOR DE BORRANDO
  deletingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    paddingHorizontal: 16,
    gap: 12,
  },
  deletingTextBold: {
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 1,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  deletingTextSmall: {
    fontSize: 12,
    fontWeight: '500',
    color: '#FFFFFF',
    marginTop: 2,
    opacity: 0.9,
  },
  // Botones de acción rápida
  quickActionsRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  quickActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
  },
  quickActionBtnPhone: {
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  quickActionText: {
    fontSize: 12,
    fontWeight: '600',
  },
  riskBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  riskBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
});
